FarmaSupply/Controllers/HomeController.cs
using FarmaSupply.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using FarmaSupply.Utils;

namespace FarmaSupply.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            EscribirLog.escribirEnFicheroLog("[INFO] Entrando en el método  Index() de la clase HomeController");

            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FarmaSupply/Controllers/RegistroController.cs
using FarmaSupply.DTO;
using FarmaSupply.Servicios;
using FarmaSupply.Utils;
using Microsoft.AspNetCore.Mvc;



namespace FarmaSupply.Controllers
{
    public class RegistroController:Controller
    {
        private readonly IUsuarioServicio _usuarioServicio;

        public RegistroController(IUsuarioServicio usuarioServicio)
        {
            _usuarioServicio = usuarioServicio;
        }

        [HttpGet]
        [Route("/auth/crear-cuenta")]
        public IActionResult RegistrarGet()
        {
            try
            {
                EscribirLog.escribirEnFicheroLog("[INFO] Entrando en el método RegistrarGet() de la clase RegistroController");

                UsuarioDTO usuarioDTO = new UsuarioDTO();
                return View("~/Views/Home/registro.cshtml", usuarioDTO);

            }
            catch (Exception e)
            {
                ViewData["error"] = "Error al procesar la solicitud. Por favor, inténtelo de nuevo.";
                EscribirLog.escribirEnFicheroLog("[ERROR] Se lanzó una excepción en el método RegistrarGet() de la clase RegistroController: " + e.Message + e.StackTrace);
                return View("~/Views/Home/registro.cshtml");
            }
        }

        [HttpPost]
        [Route("/auth/crear-cuenta")]
        public IActionResult RegistrarPost(UsuarioDTO usuarioDTO)
        {
            try
            {
                EscribirLog.escribirEnFicheroLog("[INFO] Entrando en el método RegistrarPost() de la clase RegistroController");

                UsuarioDTO nuevoUsuario = _usuarioServicio.registrarUsuario(usuarioDTO);

                if (nuevoUsuario.EmailUsuario == "EmailNoConfirmado")
                {
                    ViewData["EmailNoConfirmado"] = "Ya existe un usuario registrado con ese email pero con la cuenta sin verificar";
                    EscribirLog.escribirEnFicheroLog("[INFO] Saliendo del método RegistrarGet() de la clase RegistroController. " + ViewData["EmailNoConfirmado"]);
                    return View("~/Views/Home/login.cshtml");

                }
                else if (nuevoUsuario.EmailUsuario == "EmailRepetido")
                {
                    ViewData["EmailRepetido"] = "Ya existe un usuario con ese email registrado en el sistema";
                    EscribirLog.escribirEnFicheroLog("[INFO] Saliendo del método RegistrarGet() de la clase RegistroController. " + ViewData["EmailRepetido"]);
                    return View("~/Views/Home/registro.cshtml");
                }
                else
                {
                    ViewData["MensajeRegistroExitoso"] = "Registro del nuevo usuario OK";
                    EscribirLog.escribirEnFicheroLog("[INFO] Saliendo del método RegistrarGet() de la clase RegistroController. " + ViewData["MensajeRegistroExitoso"]);
                    return View("~/Views/Home/login.cshtml");
                }


            }
            catch (Exception e)
            {
                ViewData["error"] = "Error al procesar la solicitud. Por favor, inténtelo de nuevo.";
                EscribirLog.escribirEnFicheroLog("[ERROR] Se lanzó una excepción en el método RegistrarPost() de la clase  RegistroController: " + e.Message + e.StackTrace);
                return View("~/Views/Home/registro.cshtml");
            }
        }
    }
}

FarmaSupply/Controllers/TiendaController.cs
using FarmaSupply.DTO;
using FarmaSupply.Servicios;
using FarmaSupply.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FarmaSupply.Controllers
{ /// <summary>
  /// Controlador para gestionar las peticiones HTTP POST y GET relacionadas con las tiendas de un usuario.
  /// </summary>
    public class TiendaController : Controller
    {
        private readonly IUsuarioServicio _usuarioServicio;
        private readonly ITiendaServicio _tiendaServicio;

        public TiendaController(IUsuarioServicio usuarioServicio, ITiendaServicio tiendaServicio)
        {
            _usuarioServicio = usuarioServicio;
            _tiendaServicio = tiendaServicio;
        }


        /// <summary>
        /// Método para mostrar las tiendas asociadas al usuario autenticado.
        /// </summary>
        /// <returns>La vista de "listadoTiendas.cshtml" con la lista de tiendas del usuario.</returns>
        [Authorize]
        [HttpGet]
        [Route("/privada/listadoTiendas")]
        public IActionResult MostrarMisTiendas()
        {

            try
            {
                EscribirLog.escribirEnFicheroLog("[INFO] Entrando en el método MostrarMisTiendas() de la clase TiendaController");

                string? emailDelUsuario = User.Identity?.Name;
                UsuarioDTO usuarioSesionActual = _usuarioServicio.obtenerUsuarioPorEmail(emailDelUsuario);

                if (usuarioSesionActual != null)
                {

                    List<TiendaDTO> misTiendas = _tiendaServicio.obtenerTiendasPorPropietarioId(usuarioSesionActual.Id);

                    if (misTiendas != null && misTiendas.Count > 0)
                    {
                        ViewBag.MisTiendas = misTiendas;
                    }
                }
                EscribirLog.escribirEnFicheroLog("[INFO] Saliendo del método MostrarMisTiendas() de la clase TiendaController");
                return View("~/Views/Home/listadoTiendas.cshtml");
            }
            catch (Exception e)
            {
                ViewData["error"] = "Error al procesar la solicitud. Por favor, inténtelo de nuevo.";
                EscribirLog.escribirEnFicheroLog("[ERROR] Se lanzó una excepción en el método MostrarMisTiendas() de la clase TiendaController: " + e.Message + e.StackTrace);
                return View("~/Views/Home/listadoTiendas.cshtml");
            }
        }

        /// <summary>
        /// Método para mostrar el formulario de registro de una nueva tienda.
        /// </summary>
        /// <returns>La vista de "registroTienda.cshtml" con el formulario para agregar una nueva tienda.</returns>
        [Authorize]
        [HttpGet]
        [Route("/privada/registroTienda")]
        public IActionResult RegistrarTiendaGet()
        {
            try
            {
                EscribirLog.escribirEnFicheroLog("[INFO] Entrando en el método RegistrarTiendaGet() de la clase TiendasController");

                string emailDelUsuario = User.Identity.Name;
                UsuarioDTO usuarioSesionActual = _usuarioServicio.obtenerUsuarioPorEmail(emailDelUsuario);
                TiendaDTO nuevaTienda = new TiendaDTO();
                nuevaTienda.IdPropietario = usuarioSesionActual.Id;

                EscribirLog.escribirEnFicheroLog("[INFO] Saliendo del método RegistrarTiendaGet() de la clase TiendasController");
                return View("~/Views/Home/registroTienda.cshtml", nuevaTienda);
            }
            catch (Exception e)
            {
                ViewData["error"] = "Error al procesar la solicitud. Por favor, inténtelo de nuevo.";
                EscribirLog.escribirEnFicheroLog("[ERROR] Se lanzó una excepción en el método RegistrarTiendaGet() de la clase TiendasController: " + e.Message + e.StackTrace);
                return View("~/Views/Home/home.cshtml");
            }
        }

        /// <summary>
        /// Método para procesar el formulario de registro de una nueva tienda.
        /// </summary>
        /// <param name="tiendaDTO">Objeto DTO que contiene los datos de la nueva tienda a registrar.</param>
        /// <returns>La vista de "listadoTiendas.cshtml" con un mensaje indicando el resultado del registro.</returns>
        [Authorize]
        [HttpPost]
        [Route("/privada/registroTienda")]
        public IActionResult RegistrarTiendaPost(TiendaDTO tiendaDTO)
        {
            try
            {
                EscribirLog.escribirEnFicheroLog("[INFO] Entrando en el método RegistrarTiendaPost() de la clase TiendasController");


                string emailDelUsuario = User.Identity.Name;
                UsuarioDTO usuarioSesionActual = _usuarioServicio.obtenerUsuarioPorEmail(emailDelUsuario);
                tiendaDTO.IdPropietario = usuarioSesionActual.Id;
                TiendaDTO nuevaTienda = _tiendaServicio.registrarTienda(tiendaDTO);

                if (nuevaTienda != null && nuevaTienda.DireccionTienda != null)
                {
                    // Si el usuario y el DNI no son null es que el registro se completo
                    // correctamente
                   
                   
                    ViewData["altaTiendaExito"] = "Alta de la tienda en el sistema OK";
                    List<TiendaDTO> misTiendas = _tiendaServicio.obtenerTiendasPorPropietarioId(tiendaDTO.IdPropietario);
                    ViewBag.MisTiendas = misTiendas;
                    EscribirLog.escribirEnFicheroLog("[INFO] Saliendo del método RegistrarTiendaPost() de la clase TiendasController");
                    return View("~/Views/Home/listadoTiendas.cshtml");

                }
                else
                {
                    // Se verifica si la direccion ya existe para mostrar error personalizado en la vista
                    if (tiendaDTO.DireccionTienda == null)
                    {
                        ViewData["altaTiendaErrorDireccion"] = "Ya existe una tienda en esa dirección";
                        List<TiendaDTO> misTiendas = _tiendaServicio.obtenerTiendasPorPropietarioId(tiendaDTO.IdPropietario);
                        ViewBag.MisTiendas = misTiendas;
                        EscribirLog.escribirEnFicheroLog("[INFO] Saliendo del método RegistrarTiendaPost() de la clase TiendasController");
                        return View("~/Views/Home/registroTienda.cshtml");

                    }
                    else
                    {

                        ViewData["altaTiendaErrorNombre"] = "Ya existe una tienda con ese nombre";
                        List<TiendaDTO> misTiendas = _tiendaServicio.obtenerTiendasPorPropietarioId(tiendaDTO.IdPropietario);
                        ViewBag.MisTiendas = misTiendas;
                        EscribirLog.escribirEnFicheroLog("[INFO] Saliendo del método RegistrarTiendaPost() de la clase TiendasController");
                        return View("~/Views/Home/registroTienda.cshtml");

                    }
                }
                   
              
            }
            catch (Exception e)
            {
                ViewData["error"] = "Error al procesar la solicitud";
                EscribirLog.escribirEnFicheroLog("[ERROR] Se lanzó una excepción en el método RegistrarTiendaPost() de la clase TiendasController: " + e.Message + e.StackTrace);
                return View("~/Views/Home/home.cshtml");
            }
        }

        /// <summary>
        /// Método para eliminar una tienda existente.
        /// </summary>
        /// <param name="id">El ID de la tienda a eliminar.</param>
        /// <returns>La vista de "listadoTiendas.cshtml" con un mensaje indicando el resultado de la eliminación.</returns>
        [Authorize]
        [HttpGet]
        [Route("/privada/eliminar-tienda/{id}")]
        public IActionResult EliminarTienda(long id)
        {
            try
            {
                EscribirLog.escribirEnFicheroLog("[INFO] Entrando en el método EliminarTienda() de la clase TiendasController");

                TiendaDTO tienda = _tiendaServicio.buscarPorId(id);

                if (tienda != null)
                {
                    _tiendaServicio.eliminarTienda(id);
                    List<TiendaDTO> misTiendas = _tiendaServicio.obtenerTiendasPorPropietarioId(tienda.IdPropietario);

                    if (misTiendas != null && misTiendas.Count > 0)
                    {
                        ViewBag.MisTiendas = misTiendas;
                    }

                    ViewData["eliminacionCorrecta"] = "La tienda se ha eliminado correctamente";
                }

                EscribirLog.escribirEnFicheroLog("[INFO] Saliendo del método EliminarTienda() de la clase TiendasController. " + ViewData["eliminacionCorrecta"]);
                return View("~/Views/Home/listadoTiendas.cshtml");
            }
            catch (Exception e)
            {
                ViewData["error"] = "Error al procesar el borrado de la tienda";
                EscribirLog.escribirEnFicheroLog("[ERROR] Se lanzó una excepción en el método EliminarTienda() de la clase TiendasController: " + e.Message + e.StackTrace);
                return View("~/Views/Home/listadoTiendas.cshtml");
            }
        }

    }
}

FarmaSupply/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

  
    <!-- Hero Section Starts -->
    <section id="hero">
        <div class="hero container py-5 my-5">
            <div class="row flex-lg-row-reverse align-items-center g-5 mt-2 py-5">
                <div class="col-10 col-sm-8 col-lg-6 py-md-5 my-md-5">
                    <img src="/css/assets/scooter.png" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes"
                         width="700" height="500" loading="lazy">
                </div>
                <div class="col-lg-6 py-md-5 my-md-5">
                    <h1 class=" lh-1 mb-3">Agiliza tu logística farmacéutica</h1>
                    <ul class="list-unstyled my-5">
                        <li class="my-2">
                            <h5>Soluciones rápidas y seguras para el suministro de productos médicos en Sevilla. </h5>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

FarmaSupply/Views/Home/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

FarmaSupply/Views/Home/home.cshtml
@model FarmaSupply.DTO.UsuarioDTO
@{
    ViewData["Title"] = "Home";
    var noAdmin = ViewData["noAdmin"] as string;
    var noSePuedeEliminar = ViewData["noSePuedeEliminar"] as string;
    var error = ViewData["error"] as string;
}

<section id="hero">
    <div class="hero container py-5 my-5">
        <div class="row flex-lg-row-reverse align-items-center g-5 mt-2 py-5">
            <div class="col-10 col-sm-8 col-lg-6 py-md-5 my-md-5">
                <img src="~/css/assets/scooter.png" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes"
                     width="700" height="500" loading="lazy">
            </div>
            <div class="col-lg-6 py-md-5 my-md-5">
                <h3 class="text-dark text-center mt-5">
                    
                        <span>Bienvenido a FarmaSupply</span>
                    
                </h3>
                <br>

                @if (User.IsInRole("ROLE_USER"))
                {
                    <a asp-controller="Tienda" asp-action="MostrarMisTiendas" class="btn btn-outline-dark btn-lg" role="button">Mis tiendas</a>
                }
            </div>
        </div>
    </div>
</section>

@if (!string.IsNullOrEmpty(noAdmin))
{
    <script>
        mostrarNotificacion("¡Recurso prohibido!", "No tiene los permisos suficientes para acceder a este recurso", 'error');
    </script>
}

@if (!string.IsNullOrEmpty(noSePuedeEliminar))
{
    <script>
        mostrarNotificacion("¡Error!", "No se puede eliminar a un usuario con permisos de administrador", 'error');
    </script>
}

@if (!string.IsNullOrEmpty(error))
{
    <script>
        mostrarNotificacion("¡Error!", "Ocurrió un error no esperado, inténtelo de nuevo", 'error');
    </script>
}

FarmaSupply/Views/Home/listadoTiendas.cshtml
@model FarmaSupply.DTO.TiendaDTO

@{
    ViewData["Title"] = "listado";
    
    var eliminacionCorrecta = ViewData["eliminacionCorrecta"] as string;
    var eliminacionError = ViewData["error"] as string;
    var altaTiendaExito = ViewData["altaTiendaExito"] as string;
   
    
}


    <div class="container py-4 mt-5">
        <div class="card bg-light">
        
            <div class="card-header">
            
                <h4>Listado de tus tiendas</h4>
            </div>
        
      
            <div class="card-body">
            @if (ViewBag.MisTiendas!=null)
            {
                <h4 class="card-title">
                    <a asp-controller="Tienda" asp-action="RegistrarTiendaGet" role="button" class="btn btn-outline-dark mx-2">Registrar tienda</a>
                </h4>
                <table class="table table-striped table-bordered">
                    <thead class="thead-inverse">
                        <tr>
                            <th class="tableCustom">id</th>
                            <th class="tableCustom">Nombre tienda</th>
                            <th class="tableCustom">Dirección</th>
                            <th class="tableCustom">Código postal</th>
                           
                            <th class="tableCustom"></th>
                        
                            
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var tienda in ViewBag.MisTiendas)
                        {
                            <tr>
                                <td>@tienda.Id</td>
                                <td>@tienda.NombreTienda</td>
                                <td>@tienda.DireccionTienda</td>
                                <td>@tienda.CodigopostalTienda</td>
                               
                                <td>
                                    <a class="btn btn-danger" data-id="@tienda.Id" onclick="confirmarEliminarTienda(event)">
                                        <i class="bi bi-trash"> Eliminar</i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <h5 class="card-title text-center text-danger">No hay tiendas registradas</h5>
            }
        </div>
    </div>


   
 @if (!string.IsNullOrEmpty(altaTiendaExito))
 {
        <script>
        mostrarNotificacion("¡La tienda fue registrada!", "Se ha dado de alta su nueva tienda correctamente", 'info');
        </script>
 }

 
@if (!string.IsNullOrEmpty(eliminacionCorrecta))
{
    <script>
        mostrarNotificacion("¡Tienda eliminada!", "La tienda ha sido eliminada correctamente", 'success');
    </script>
}
@if (!string.IsNullOrEmpty(eliminacionError))
{
    <script>
        mostrarNotificacion("¡Error!", "Ocurrio un error no esperado, intentelo de nuevo", 'error');
    </script>
}
</div>

FarmaSupply/Views/Home/login.cshtml
@model FarmaSupply.DTO.UsuarioDTO
@{
    ViewData["Title"] = "login";
    var mensajeRegistroExitoso = ViewData["MensajeRegistroExitoso"] as string;
    var cuentaVerificada = ViewData["CuentaVerificada"] as string;
    var cuentaNoVerificada = ViewData["EmailNoConfirmado"] as string;
    var yaEstabaVerificada = ViewData["yaEstabaVerificada"] as string;
    var mensajeExitoMail = ViewData["MensajeExitoMail"] as string;
    var contraseñaModificada = ViewData["ContraseñaModificadaExito"] as string;
    var mensajeErrorInicioSesion = ViewData["MensajeErrorInicioSesion"] as string;
    var recursoProhibido = ViewData["RecursoProhibido"] as string;
    var error = ViewData["error"] as string;
}



    <section id="hero">
        <div class="hero container py-5 my-5">
            <div class="row flex-lg-row-reverse align-items-center g-5 mt-2 py-5">
                <div class="col-10 col-sm-8 col-lg-6 py-md-5 my-md-5">
                    <img src="~/css/assets/scooter.png" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes"
                         width="700" height="500" loading="lazy">
                </div>
                <div class="col-lg-6 py-md-5 my-md-5">
                    <form id="loginForm" class="form-group flex-wrap p-3" method="post"
                          asp-action="ProcesarInicioSesion" asp-controller="Login" asp-for="UsuarioDTO" role="form">
                        <div class="form-input col-lg-12 my-4">
                            <label for="emailUsuario"
                                   class="form-label fs-6 text-uppercase fw-bold text-black">Email</label>
                            <input id="EmailUsuario" type="email" class="form-control ps-3" name="EmailUsuario" required>
                        </div>
                        <div class="form-input col-lg-12 my-4">
                            <label for="claveUsuario"
                                   class="form-label fs-6 text-uppercase fw-bold text-black">Contraseña</label>
                            <input name="ClaveUsuario" id="ClaveUsuario" type="password" class="form-control ps-3"
                                   required>
                        </div>
                        <div class="d-grid my-3">
                            <button class="btn btn-primary btn-lg btn-dark text-uppercase btn-rounded-none fs-6"
                                    type="submit" id="btnAcceder">
                                Acceder
                            </button>
                        
                  
                        </div>
                    </form>
                    <div class="d-grid my-3">
                    <form id="registroForm" class="form-group flex-wrap p-3" method="GET" asp-action="RegistrarPost" asp-controller="Registro">
                            <button type="submit"
                                    class="btn btn-primary btn-lg btn-dark text-uppercase btn-rounded-none fs-6">
                                Registrarse
                            </button>
                        </form>
                    </div>
                    <div class="d-grid my-3">
                    <form id="recuperacionForm" class="form-group flex-wrap p-3" asp-action="MostrarVistaIniciarRecuperacion" asp-controller="RecuperarClave"
                              method="get">
                            <button type="submit"
                                    class="btn btn-primary btn-lg btn-dark text-uppercase btn-rounded-none fs-6">
                                Recuperar
                                contraseña
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

    @if (!string.IsNullOrEmpty(mensajeRegistroExitoso))
    {
        <script>
            mostrarNotificacion("¡Email de confirmación enviado!", "Revise su bandeja de entrada y confirme su cuenta de correo electrónico.", 'info');
        </script>
    }

    @if (!string.IsNullOrEmpty(cuentaVerificada))
    {
        <script>
            mostrarNotificacion("¡Cuenta verificada!", "La cuenta ha sido confirmada correctamente. Ya puede iniciar sesión", 'success');
        </script>
    }
    @if (!string.IsNullOrEmpty(cuentaNoVerificada))
    {
        <script>
            mostrarNotificacion("¡Debe confirmar su correo electrónico!", "Para poder iniciar sesión, antes debe confirmar su cuenta de correo electrónico. Revise su bandeja de entrada", 'error');
        </script>
    }
    @if (!string.IsNullOrEmpty(mensajeExitoMail))
    {
        <script>
            mostrarNotificacion("¡Email de recuperación enviado!", "Revise su bandeja de entrada y sigua las instrucciones para restablecer su contraseña", 'info');
        </script>
    }
    @if (!string.IsNullOrEmpty(yaEstabaVerificada))
    {
        <script>
            mostrarNotificacion("¡Se encuentra registrado y vericado!", "Puede acceder y hacer uso de su cuenta", 'info');
        </script>
    }
    @if (!string.IsNullOrEmpty(contraseñaModificada))
    {
        <script>
            mostrarNotificacion("¡Contraseña modificada con exito!", "Ya puede iniciar sesión con su nueva contraseña", 'success');
        </script>
    }
    @if (!string.IsNullOrEmpty(mensajeErrorInicioSesion))
    {
        <script>
            mostrarNotificacion("¡No se pudo iniciar sesión!", "Credenciales introducidas incorrectas o cuenta de email no verificada", 'error');
        </script>
    }
    @if (!string.IsNullOrEmpty(recursoProhibido))
    {
        <script>
            mostrarNotificacion("¡Prohibido!", "No tiene permiso para acceder a este recurso", 'error');

        </script>
    }
    @if (!string.IsNullOrEmpty(error))
    {
        <script>
            mostrarNotificacion("¡Error!", "Ocurrio un error no esperado, intentelo de nuevo", 'error');
        </script>
    }

FarmaSupply/Views/Home/registroTienda.cshtml
@model FarmaSupply.DTO.TiendaDTO

@{
    ViewData["Title"] = "registro";
    var altaTiendaError = ViewData["error"] as string;
    var altaTiendaErrorDireccion = ViewData["altaTiendaErrorDireccion"] as string;
    var altaTiendaErrorNombre = ViewData["altaTiendaErrorNombre"] as string;
    
}

    <section id="hero">
        <div class="hero container py-5 my-5">
            <div class="row flex-lg-row-reverse align-items-center g-5 mt-2 py-5">
                <div class="col-10 col-sm-8 col-lg-6 py-md-5 my-md-5">
                    <img src="~/css/assets/scooter.png" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes"
                         width="700" height="500" loading="lazy">
                </div>
                <div class="col-lg-6 py-md-5 my-md-5">
                <form id="form4" class="form-group flex-wrap p-3" asp-action="RegistrarTiendaPost" asp-controller="Tienda" method="post" asp-for="UsuarioDTO">
                        <input type="hidden" name="returnUrl" value="@TempData["ReturnUrl"]" />
                        <div class="form-input col-lg-12 my-4">
                        <label for="NombreTienda" class="form-label fs-6 text-uppercase fw-bold text-black">Nombre tienda</label>
                        <input type="text" id="NombreTienda" name="NombreTienda" class="form-control ps-3" required />
                                   
                        </div>
                        <div class="form-input col-lg-12 my-4">
                        <label for="DireccionTienda" class="form-label fs-6 text-uppercase fw-bold text-black">Dirección</label>
                        <input type="text" id="DireccionTienda" name="DireccionTienda" class="form-control ps-3" required />
                        </div>
                        <div class="form-input col-lg-12 my-4">
                        <label for="CodigopostalTienda" class="form-label fs-6 text-uppercase fw-bold text-black">Código postal</label>
                        <input type="text" id="CodigopostalTienda" name="CodigopostalTienda" class="form-control ps-3" required />
                        </div>
                  
                        
                        
                        <div class="d-grid my-3">
                            <button class="btn btn-primary btn-lg btn-dark text-uppercase btn-rounded-none fs-6"
                                    type="submit" id="btnRegistro">
                                Registrar tienda
                            </button>
                        
                        </div>
                    </form>
                </div>
            </div>
        </div>

    @if (!string.IsNullOrEmpty(altaTiendaError))
    {
        <script>
            mostrarNotificacion("¡Error al registrar tu tienda!", "No se pudo registrar su nueva tienda, intentelo de nuevo.", 'error');
        </script>
    }
    @if (!string.IsNullOrEmpty(altaTiendaErrorDireccion))
    {
        <script>
            mostrarNotificacion("¡Error al registrar tu tienda!", "Ya existe una tienda con esa direccion", 'error');
        </script>
    }

    @if (!string.IsNullOrEmpty(altaTiendaErrorNombre))
    {
        <script>
            mostrarNotificacion("¡Error al registrar tu tienda!", "Ya existe una tienda con ese nombre", 'error');
        </script>
    }
    </section>